//createProduct
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "images": ["http://example.com","http://example.com"],
    "name": "100번째 상품",
    "description": "축하합니다! 판다마켓의 역사에 기록된 100번째 상품입니다.",
    "price": 100,
    "tags": ["테스트", "상품"]
}

//loadOneProduct
GET http://localhost:3000/api/products/1
//loadProductList
GET http://localhost:3000/api/products/
GET http://localhost:3000/api/products?page=1&pageSize=100&orderBy=recent
//editProduct
PATCH http://localhost:3000/api/products/82
Content-Type: application/json

{
    "images": ["http://example.com","http://example.com"],
    "name": "아오아오아ㅇㄴㄹㄹ",
    "description": "테스트 ㄷㄷ명",
    "price": 14,
    "tags": ["테스트", "상품", "간지나는거임ㅅㄱ"]
}
//removeProduct
DELETE http://localhost:3000/api/products/3